name: Build and Test

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  backend:
    name: Backend Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      working-directory: timelogger-backend/timelogger-web-api
      run: dotnet restore

    - name: Build
      working-directory: timelogger-backend/timelogger-web-api
      run: dotnet build --no-restore --configuration Release

    - name: Test
      working-directory: timelogger-backend/timelogger-tests
      run: dotnet test --no-build --configuration Release --verbosity normal

  frontend:
    name: Frontend Build and Test
    runs-on: ubuntu-latest
    needs: backend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'timelogger-frontend/timelogger-react-app/package-lock.json'
    
    - name: Install dependencies
      working-directory: timelogger-frontend/timelogger-react-app
      run: npm ci
    
    - name: Build
      working-directory: timelogger-frontend/timelogger-react-app
      run: npm run build
    
    - name: Test
      working-directory: timelogger-frontend/timelogger-react-app
      run: npm run test
