name: Deploy ASP.NET Core Infrastructure

on:
  workflow_dispatch
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/database

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Authenticate to Google Cloud
      run: echo "Simulating cloud authentication..."
      # uses: google-github-actions/auth@v1
      # with:
      # credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      run: echo "Setup cloud SDK..."
      # uses: google-github-actions/setup-gcloud@v1
      # with:
      #  project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Terraform Init
      run: echo "Simulating TF Init..."
      #env:
       # GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform Format
      run: echo "Simulating TF Format..."
      #run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Plan
      run: echo "Simulating TF Plan ..."
      #run: terraform plan -out=tfplan
      #env:
        # USE VARIABLES FROM VAR FILE

    - name: Terraform Apply
      run: echo "Simulating TF Apply ..."
      #run: terraform apply tfplan
      #env:
        #GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Export Terraform Outputs
      run: echo "Simulating TF Export ..."
      #id: terraform-outputs
